name: Build and Package Strategy Pattern

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          g++ \
          pkg-config \
          libgtest-dev \
          libgmock-dev \
          googletest
        
    - name: Build and Install GTest
      run: |
        cd /usr/src/googletest
        sudo cmake -S . -B build -DBUILD_GMOCK=OFF
        sudo cmake --build build
        sudo cmake --install build
        sudo ldconfig
        
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel 2
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p strategy-package/usr/bin
        cp build/strategy_demo strategy-package/usr/bin/
        
        mkdir -p strategy-package/DEBIAN
        cat <<EOF > strategy-package/DEBIAN/control
        Package: strategy-demo
        Version: 1.0-$(date +%Y%m%d%H%M)
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Demonstration of Strategy Pattern implementation
        Homepage: https://github.com/yourusername/strategy-pattern
        EOF
        
        dpkg-deb --build strategy-package
        mkdir -p dist
        mv strategy-package.deb dist/strategy-demo.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: strategy-package
        path: dist/strategy-demo.deb
        retention-days: 5
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/strategy-demo.deb
        body: |
          Automatic build of Strategy Pattern demo
          Includes:
          - Executable binary
          - DEB package
        draft: false
        prerelease: false
